gemini_auth_token: ENC[AES256_GCM,data:7fbIY9pkRPO8L9MpZtgEx6sot1Kd8PVdJJmgPWL2d7JSf6RY8cFg,iv:oAZJZJj9HV+fUfOIyTcBZMbwHoJED9N8b1DWip6lPWs=,tag:7jMmgVKHgzKjU/wrQyq6OA==,type:str]
openai_auth_token: ENC[AES256_GCM,data:xFaXOwbLIdAQcUQZu6ncXDmJyJvG9uJqEs8Oq5Wo/n789502B4Udi07cr6Zs2SIHiAAUWO3zZd5E6AV2XefLi2CCvdmdVK/s0u8Tpm8iKMhTjf4zvTsUhnxXWOLleHaEs1rd47N82IS7idfPc9f+pgWUQ1Phzsaav6wlDZAfzzx7K+5ylUxFffGNdJ2B+5t4DF0DGENyPIghM8KTmTz7bceh5gg=,iv:yVHIYTfzenJlwPxjUFcS7+pkUARaKdoqAbTGEeyqzaQ=,tag:+uiLTTM/EWIBxaUQVUd9Vw==,type:str]
groq_auth_token: ENC[AES256_GCM,data:FgPF8zs1d1I3o/W/Kljp9t7ChHg//36cSpByPXFILlAXV2+2OSd/Q9/s0rnt3ake14DBxuWmwvA=,iv:KLsCmO7j6Ate8Ktl7RZPETxuQD3HaoiEGhq1lCshl5I=,tag:v8jV222AJgo6elMkPvc/kg==,type:str]
qwen_auth_token: ENC[AES256_GCM,data:EoDRGK9Z+JiHYZPjvG2fxEhi9vlCsIJbX6yCESZxLOCGp8M=,iv:FqqWdn9MKtlB4NylKBkQIG01Fhab8lRkeb4pa3jMMtE=,tag:x60Ro8Qp73hP/nfowxvQig==,type:str]
deepseek_auth_token: ENC[AES256_GCM,data:NFfeQM5si9ybjN94K1EtWrF6LKJzxI0oPPERckUPeDHm3Jo=,iv:Z22zJiuwqYJfedpQIHALNgZKHUzm6Srr1+/IQqrr9k8=,tag:4Cq+53YwMsRYZXgMQ2YqeA==,type:str]
tabby_auth_token: ENC[AES256_GCM,data:IWU7+gwQZOcXppXn2O5ZcV2zJFisRwdSg/R2tT3clHbzUHUtiQ==,iv:AWqpTpXzLYqQ+W8jSoRTQ6UTauD0WQ1lXYcF4LKmVWI=,tag:K0iAduDbPPwHfC63DgmADg==,type:str]
mistral_auth_token: ENC[AES256_GCM,data:8k/2GGOAWa5lmTBZjlTXwZTtWHFtoRHJBsJOJWdUrOQ8ScI=,iv:TZbV/B9qPdJIZU04bckFd6NBCA/Sbz3spbxSeX+kMt8=,tag:tyIXb2YhMHk02fvjmm8tEA==,type:str]
sops:
    age:
        - recipient: age1azlqlugvnzqvt4j4d9secmus8cy8gu20fnv8erdevw7ytrfp4y3sjhgnj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N0lrczRBTTBKZm1TMXdQ
            ODc1WEVrR3gydXQvK1dUOXlzTXZVYnpXSVgwCitHY0k3eVhtS3d0eE9ZNDJGSWlz
            U1ZBQjJWcVBTMjlNc2h3QXRUSzFuVkkKLS0tIGVLSko2NVcxbDdpcDlWdk53YnhM
            cloxVnhIWExzbTRrUTI2MXJ0eVBwd2cKd/V67Z2wnh9leCafxUWYyRlZ5steGcwM
            qDHF3R++ptHwnajXiG9AVTF80rJtSfJWnGFKVsj5arLK5AtKwwmNpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T02:23:06Z"
    mac: ENC[AES256_GCM,data:uUmk7aJdlc6LWK6ea3bFWbzymDcb79g0WY1tS3kokNllYNlVvT7EZ0YdTSu3fhd7fl9BkWabz06iCjMoN80JdnXbQ/b+yMY6jBX2aWhExhCSlUjpELwXibnacibuQDgAhPEL+Wt5K5UU0T/U1sDlW9kyHVnJ4YKF4uIk6t9qmhI=,iv:QoJR7TQHcNxf8obcEYWSyKsdv+JPF/WUzdy+kT1y/RU=,tag:r7gDkMT3BL1ZDAZlTEI6/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
