tabby_auth_token: ENC[AES256_GCM,data:99DG/BShOG0PqykAPhNsT04iBWjSvp1n2Bz5ZUCCz/w8H49/tQ==,iv:3utZKHVnWfiFihxS2RKiCVOnfOWbmZ5fFghkaR+Ukpc=,tag:UImAQxVAvwr3pdjnqN3q0Q==,type:str]
gemini_auth_token: ENC[AES256_GCM,data:TLQ7e0WB5G7vJPHTMF/kS2qSnAIMAQZkpAeaTwV9qw1+QKCDRw/f,iv:DS2BOyVhDrSq34YfrkvpHHq2DqDId8x2J1j4YiWYtCQ=,tag:WJoUPUUQ+pF2tofSwR3U6g==,type:str]
openai_auth_token: ENC[AES256_GCM,data:GkLnkOww8mkNdmL26/rndsyxgL/sRIYvbyzCzCIy2kwbmUIYPZZoon5UoJZQtY4SSzHqE3GqFEPrXWPlXevWTSwL2hcmt5p01P23n3E1IGSrSSc382/xEq20PsAZvCKbtiWq39PXn/n1sqJhs/sDXOcGhtedkr1se4/a7VCrkGfrNu4rq/NNbFfmHRFq+zRzCzToFA8mI4Ybwh0QQIwLrGuZND4=,iv:mvidqwpB0ZhMLKVse0KM8w5OYlNgvu1czTDBLdEsiTM=,tag:E/uaJ96s0uQlDeuKtn1sRA==,type:str]
deepseek_auth_token: ENC[AES256_GCM,data:Y3A7V2pVkIAh8gqOihQVOfhjl48yQg5+oqwwTpIwUoml7BY=,iv:2n2K8WaTP3QGz6LwYzbivnAd4qIoot7PAIZ1IVFABFA=,tag:vGpwQrHhDWNe1hI9xyrq2A==,type:str]
sops:
    age:
        - recipient: age1t9jnlavgssytkgm95grf8hkmkw7hjmfrtk7vtjgmjg2dufrnt5csrngujz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM0h2RjIvRTZEaHd6REo5
            ZFJlOGRRRk5WaFRoRlNtRkFjNzJldngrRVg0CnQrOVNTeWpib1BnT0VkTGQ2NHAx
            TjM1dTFaaFZCR0JUdzF5SUVnc3FSOTQKLS0tIEU5bDZuM2pVSkovU1Y1SFRuSW9q
            c29XZHVDS3Q0WERtZ1Y1NWZRQjc3L2MK1jEZx9qaXJfI479HWoNXpp4EzoD0rHTs
            8KT/l2XHD1hhBktyLezMA0caXpHwF/euiABL6FyWOjbWYhjmjWYwOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T00:36:49Z"
    mac: ENC[AES256_GCM,data:UCaBous7Cd9JN6B3db68CPreFEXp/L734Sybpl5/f1YHiHIb1WxWw9f60XYGuTUQKkz5U8U/mb2uvEDS2aKyW/9cVR/zMe38ZOKdQYlbnDZoRe5Dsx6uJPAsGlFNWAJKeLCI6hxJJYZIB0l1teQwGNWnfqpqGAQQKckVjtufOqM=,iv:48O91F6faarcEAU4ui7UdFDJpCrvQJEqxYvwYjimlI0=,tag:iEN+YMZ7VHFG5WHFSLh1LA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
