tabby_auth_token: ENC[AES256_GCM,data:99DG/BShOG0PqykAPhNsT04iBWjSvp1n2Bz5ZUCCz/w8H49/tQ==,iv:3utZKHVnWfiFihxS2RKiCVOnfOWbmZ5fFghkaR+Ukpc=,tag:UImAQxVAvwr3pdjnqN3q0Q==,type:str]
sops:
    age:
        - recipient: age1t9jnlavgssytkgm95grf8hkmkw7hjmfrtk7vtjgmjg2dufrnt5csrngujz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM0h2RjIvRTZEaHd6REo5
            ZFJlOGRRRk5WaFRoRlNtRkFjNzJldngrRVg0CnQrOVNTeWpib1BnT0VkTGQ2NHAx
            TjM1dTFaaFZCR0JUdzF5SUVnc3FSOTQKLS0tIEU5bDZuM2pVSkovU1Y1SFRuSW9q
            c29XZHVDS3Q0WERtZ1Y1NWZRQjc3L2MK1jEZx9qaXJfI479HWoNXpp4EzoD0rHTs
            8KT/l2XHD1hhBktyLezMA0caXpHwF/euiABL6FyWOjbWYhjmjWYwOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T10:07:07Z"
    mac: ENC[AES256_GCM,data:KplgPApU+40g/9DHuP4Z9iFXbuT2khovh6pw9Iq2O/1NiqTeHpmJyMxxp1uqLcoXK0OkTi/wViGqLj11y1yrT+SZoUP+Fh03u81nJNVMOA4tfDG7qbOVrciLyFX+YtF5UyhJMHzLNyABRP1eBo8UyWKIg2GEk40ZxsYZ9jajn+4=,iv:a+40swrmpz2QmEy1EgWRSuKhJbiSG4wvi6OKPhZ9uFs=,tag:172YGjl0+znVC5DE6lDX7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
