tabby_auth_token: ENC[AES256_GCM,data:99DG/BShOG0PqykAPhNsT04iBWjSvp1n2Bz5ZUCCz/w8H49/tQ==,iv:3utZKHVnWfiFihxS2RKiCVOnfOWbmZ5fFghkaR+Ukpc=,tag:UImAQxVAvwr3pdjnqN3q0Q==,type:str]
gemini_auth_token: ENC[AES256_GCM,data:TLQ7e0WB5G7vJPHTMF/kS2qSnAIMAQZkpAeaTwV9qw1+QKCDRw/f,iv:DS2BOyVhDrSq34YfrkvpHHq2DqDId8x2J1j4YiWYtCQ=,tag:WJoUPUUQ+pF2tofSwR3U6g==,type:str]
openai_auth_token: ENC[AES256_GCM,data:GkLnkOww8mkNdmL26/rndsyxgL/sRIYvbyzCzCIy2kwbmUIYPZZoon5UoJZQtY4SSzHqE3GqFEPrXWPlXevWTSwL2hcmt5p01P23n3E1IGSrSSc382/xEq20PsAZvCKbtiWq39PXn/n1sqJhs/sDXOcGhtedkr1se4/a7VCrkGfrNu4rq/NNbFfmHRFq+zRzCzToFA8mI4Ybwh0QQIwLrGuZND4=,iv:mvidqwpB0ZhMLKVse0KM8w5OYlNgvu1czTDBLdEsiTM=,tag:E/uaJ96s0uQlDeuKtn1sRA==,type:str]
deepseek_auth_token: ENC[AES256_GCM,data:Y3A7V2pVkIAh8gqOihQVOfhjl48yQg5+oqwwTpIwUoml7BY=,iv:2n2K8WaTP3QGz6LwYzbivnAd4qIoot7PAIZ1IVFABFA=,tag:vGpwQrHhDWNe1hI9xyrq2A==,type:str]
groq_auth_token: ENC[AES256_GCM,data:wG44id8McL9N+CSPBeVfWSskaSL+zi8+x53XuANoVhHtxJcVHoYm6JqxUI8V3VDGVjYMkYKBp8g=,iv:tb2NVQI7W3EvEFifDCZaONJE/FU/c+akT+o2v25XRz0=,tag:K2R2F03O4/VlB8+ckvBZ1Q==,type:str]
qwen_auth_token: ENC[AES256_GCM,data:eWEKGjsR2tagtsepOznkkmpbqOHFLQ4rWL6kkykRxiZ5H70=,iv:hNE3hxJOKAI1ElWqNU9t+W0GsVkpcKRRje3i5x7XiYk=,tag:cKosC/isV+wIJAydCpkkzg==,type:str]
mistral_auth_token: ENC[AES256_GCM,data:PtkDhH1WWEqA2E5gdnh9M093d/Yel3OkrZgGucduF9c=,iv:fUZ7OyHm3V6TfZJkF0OartZh+Mnvcj7vNjhAqxj+eYg=,tag:Toh1Cm5SwLUyY+F8FAxXJg==,type:str]
deepinfra_auth_token: ENC[AES256_GCM,data:GYgwj+zMsqlaLzlC9WJ7HGjBFPo1riYGySIMjzrZO8Q=,iv:OjIo8DRpZ+9VcgW4pABVQJ1TZCEehIR57XZCkyfekP8=,tag:wLuSx3vV1MdUodZr4G/Lng==,type:str]
sops:
    age:
        - recipient: age1t9jnlavgssytkgm95grf8hkmkw7hjmfrtk7vtjgmjg2dufrnt5csrngujz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM0h2RjIvRTZEaHd6REo5
            ZFJlOGRRRk5WaFRoRlNtRkFjNzJldngrRVg0CnQrOVNTeWpib1BnT0VkTGQ2NHAx
            TjM1dTFaaFZCR0JUdzF5SUVnc3FSOTQKLS0tIEU5bDZuM2pVSkovU1Y1SFRuSW9q
            c29XZHVDS3Q0WERtZ1Y1NWZRQjc3L2MK1jEZx9qaXJfI479HWoNXpp4EzoD0rHTs
            8KT/l2XHD1hhBktyLezMA0caXpHwF/euiABL6FyWOjbWYhjmjWYwOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T02:40:55Z"
    mac: ENC[AES256_GCM,data:qzJDtFZ6ScW4nJknTCmx9rvEAMN4sYsRzj//it6k9mvV896vM9vVj2RtpTPRF9w1iwVdaQlvZqa9RoJwbdeJ3HSqfxebKiAsLOAGWVwqRz2gIVTzt/ALAOOn0M/l4mXKoom1Nj6vRK4mDg61XLa9X6qB447VS6BV2bv5TuDhohI=,iv:nrs4EFx2k3fDxanzMkQo902HvwaRVRoEyXF52LsY01M=,tag:CZcqi1I3MkYSF2xhDY/6hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
